### ISSUE TITLE
gRPC max message size control

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-api-go#161]
## Expected Behavior
gRPC transport layer of NeoFS independently understands message size restrictions.
## Current Behavior
gRPC layer relies entirely on the internal services of the node so that stream messages will not overflow restrictions.
## Possible Solution
Find the way to determine maximum message size in runtime. If message overflows the restriction, split single messages to smaller ones on client side, and restore on server side.

## Steps to Reproduce (for bugs)
Set max object size larger than maximum message size and request payload range. 

## Problems
Request signatures are signed/verified by internal services, so gRPC layer must control additional splitting/composing of messages.

**Comment by alexvanin** [comment]
As discussed with @cthulhu-rider and @realloc we can't split messages on transport layer in `neofs-api-go`. Since every message has to be signed, then split should happen before signing and it contradicts proposed solution. The only thing transport layer can do is try to find some kind of `MTU` and pass it to neofs-node serivce. 

For now we've decided to set up default message size values in `neofs-node` (4MiB) and propose to not change it in other node implementations. Also `neofs-node` has separate splitter service that chunks stream messages before passing it into signer service: https://github.com/nspcc-dev/neofs-node/pull/59

I propose to close this issue and discuss dynamic `MTU` calculation in other one if needed.
