### ISSUE TITLE
There're no well-known attributes

### ISSUE THREAD

**Issue by im-kulikov** [nspcc-dev/neofs-api-go#172]
`Object` and `Container` contains user-specific attributes (`[]*Attribute` is KeyValue) but there're no well-known attributes.

For example:
- `CreatedAt` - human-readable creation date/time (out of the box)
- `Name` - human-readable object/container name

@realloc, @alexvanin what are you think about adding constants for these attributes and the possibility to set them out of the box?

**Comment by realloc** [comment]
Let's add `Name` attribute to the well-known list in `-api` and `-spec` repos and then we can reflect that in `api-go`.

The `CreatedAt` attribute may be tricky. if it has `Epoch`, then IR can't set it because the whole structure is formed by owner and should not be changed. Owner can't predict for sure the Epoch of container being added into `Container` smart contract storage. We could get that information indirectly from the height of the block having container creation TX, but I'm not sure where to put it. Maybe in response meta headers, but that's strange.

If `CreatedAt` will have the unverified user defined date-time in some common format, then It's ok, but we need to name it somehow differently.

**Comment by im-kulikov** [comment]
In the closest future, I would like to see (SDK):
- `Object.GetName() string`
- `Object.GetCreatedAt() time.Time`
- `Container.GetName() string`
- `Container.GetCreatedAt() time.Time`

For example:
(Object/Container) -> Attributes -> Constant -> Result

**Comment by alexvanin** [comment]
Don't mind to have those attributes. There is a good point that `CreatedAt` should be renamed to emphasize that this is unverified value. Maybe something like `LocallyCreatedAt`? Or `LocalCreationTime`.

**Comment by im-kulikov** [comment]
> ... CreatedAt should be renamed ... LocallyCreatedAt? Or LocalCreationTime

Naming is not as critical to me as the fact of having

**Comment by realloc** [comment]
Need to make sure `neofs-api-go` follows changes from nspcc-dev/neofs-api#77.

**Comment by im-kulikov** [comment]
Object:
- `Filename`
- `Timestamp`

Container:
- `Name`
- `Timestamp`

**Comment by realloc** [comment]
> Object: 
>* `Filename`
>* `Timestamp`
* `Name`

What did you mean?

**Comment by im-kulikov** [comment]
> > Object:
> > 
> > * `Filename`
> > * `Timestamp`
> 
> * `Name`
> 
> What did you mean?

For object we have two useful well-known attributes : filename and timestamp

This is notice for @alexvanin to add these attributes into sdk

**Comment by realloc** [comment]
> Name isn’t useful attribute for object, that’s why I don’t add it into notice

Actually it's useful and has the same semantics and meaning as `Name` for Container. `Filename` should be used in cases like mirroring `X-Filename` http header to an object.

**Comment by im-kulikov** [comment]
> > Name isn’t useful attribute for object, that’s why I don’t add it into notice
> 
> Actually it's useful and has the same semantics and meaning as `Name` for Container. `Filename` should be used in cases like mirroring `X-Filename` http header to an object.

not quite.. for example, I can't find any useful usages for it in any of our services.

`Filename`, should be set by service and then, can be used to display for users, same as `Timestamp`

In this case, I don't see any useful usages for `Name`. As @alexvanin explained, this attribute can be used as human-readable replacement of the sha-hash
